name: Secret Input Example Workflow

on:
  workflow_dispatch:
    inputs:
      api_key:
        description: 'API Key'
        required: true
        type: secret

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print masked secret
        run: |
          echo "API Key is set"
          echo "API Key is: ${{ inputs.api_key }}"
          echo "::add-mask::${{ inputs.api_key }}"
