name: Secret Input Example Workflow

on:
  workflow_dispatch:
    inputs:
      api_key:
        description: 'API Key'
        required: true
        type: string
      api_key_secret:
        description: 'API Key'
        required: true
        type: secret

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print masked secret
        run: |
            the_secret=${{ inputs.api_key }} 
            echo "::add-mask::$the_secret"
            echo "secret-key=$the_secret" >> "$GITHUB_OUTPUT"
      - name: Print masked secret
        run: |
            the_secret=${{ inputs.api_key_secret }} 
            echo "::add-mask::$the_secret"
            echo "secret-key-1=$the_secret" >> "$GITHUB_OUTPUT"
            
      - name: Use that secret output (protected by a mask)
        run: |
          echo "the secret number is ${{ steps.sets-a-secret.outputs.secret-key }}"
          echo "the secret number is ${{ steps.sets-a-secret.outputs.secret-key-1 }}"

