name: Testresult upload
on:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  build-test:
    permissions:
      checks: write
      pull-requests: write
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn --batch-mode clean install 2> report-banner.txt

      - name: Publish Cucumber Results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2.16.1
        with:
          files: |
            target/**/cucumber-junit.xml

      - name: Get Cucumber Report
        if: always()
        id: get-cucumber-report
        run: |
          grep -E "^│.*│$" report-banner.txt > cucumber-report.txt
          echo "report=$(cat cucumber-report.txt)" >> $GITHUB_OUTPUT
            
      - name: Find previous comment in PR
        if: always() && github.event_name == 'pull_request'
        uses: peter-evans/find-comment@v3
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'Cucumber Results:'

      - name: Create or update comment in PR
        if: always() && github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Cucumber Results:
            ${{ steps.get-cucumber-report.outputs.report }}
          edit-mode: replace
