name: Testresult upload
on:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  build-test:
    permissions:
      checks: write
      pull-requests: write
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn --batch-mode clean install

      - name: Publish Cucumber Results
        uses: EnricoMi/publish-unit-test-result-action@v2.12.0
        if: always()
        with:
          files: |
            target/**/cucumber-junit.xml
